post:
  tags:
    - Task
  description: Creates a Task
  operationId: createTask
  requestBody:
    content:
      application/json:
        schema:
          $ref: components.yml#/components/schemas/TaskIn
  responses:
    '201':
      description: Task created successfully
      content:
        application/json:
          schema:
            $ref: components.yml#/components/schemas/TaskOut
          examples:
            default:
              value: {
                id: 61435636c398c785ab8b2cb7,
                description: Walk the dog,
                group: {
                  id: 61435636c398c785ab8b2cb6,
                  name: home,
                  description: homedescriptiontoolargeomg
                },
                assignedTo: notabug,
                effort: 5,
                done: false,
                dueDate: 2021-12-12
              }

    '400':
      description: Due date already passed
      content:
        application/json:
          schema:
            $ref: ../common.yml#/components/schemas/ErrorOut
          examples:
            default:
              value: {
                code: F0400,
                description: Due date already passed
              }

    '500':
      description: Generic error
      content:
        application/json:
          schema:
            $ref: ../common.yml#/components/schemas/ErrorOut
          examples:
            default:
              value: {
                code: F0400,
                description: Internal error please contact the administrator
              }