server:
  port: ${SPRING_PORT:9900}
  application.name: GRHAUS
  servlet.context-path: /grhaus

management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: '*'
  endpoint:
    info.enabled: true
    health.enabled: true
    shutdown.enabled: ${SPRING_ACTUATOR_SHUTDOWN_ENABLED:false}

springdoc:
  swagger-ui:
    path: /swagger-ui


spring:
  profiles:
    active: ${SPRING_PROFILE:test}