openapi: 3.0.3

info:
  title: GRhaus - Group Task Assignment & Scheduling
  description: API for Group, User and Task
  version: 1.0.0
  contact:
    name: Ulises Javier Franco
    email: ulisesjavierfranco@gmail.com

servers:
  - url: http://localhost:9900/grhaus
    description: localhost

tags:
- name: Group
- name: User
- name: Task

paths:

  /1/group:
    $ref: group/routes.yml

  /1/group/{groupId}:
    $ref: group/id_routes.yml

  /1/tasks/:
    $ref: task/query_routes.yml

  /1/task:
    $ref: task/routes.yml

  /1/task/{taskId}:
    $ref: task/id_routes.yml

  /1/user:
    $ref: user/routes.yml

  /1/user/{userId}:
    $ref: user/id_routes.yml